# Generated by Django 4.1.4 on 2022-12-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_simulator', '0003_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='cash',
            field=models.FloatField(default=10000),
        ),
    ]
